keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:real-estate}
  client-id: ${KEYCLOAK_CLIENT_ID:real-estate-credential-id}
  grant-type: ${KEYCLOAK_GRANT_TYPE:password}
  username: ${KEYCLOAK_USERNAME:zote}
  password: ${KEYCLOAK_PASSWORD:zote}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:mAONFHck6LiZewGnPR6ixTqZKBVEJjw2}
  auth-server-url: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/token